/** AUTO-GENERATED — npm run sync:esim (Google Sheet (data/esim/sheets.json)) */
import type { EsimProduct } from '../types';
import { enrichEsimOffers } from './esimOfferEnrich';

/** CSV sync 시각 — npm run sync:esim 할 때마다 갱신 */
export const ESIM_OFFERS_UPDATED_AT = '2026-06-18T03:30:42.919Z';

const RAW: EsimProduct[] = [
  {
    id: 'usimsa-JP-unlimited-lte-1d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 4000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-1d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 3800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-1d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 3300,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-1d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 3000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-1d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 2600,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-1d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 2000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-1d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 1500,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-2d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 7400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-2d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 6900,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-2d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 6000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-2d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 5300,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-2d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 4400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-2d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 3500,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-2d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 2200,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-3d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 9900,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-3d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 9100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-3d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 8000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-3d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 7000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-3d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 5900,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-3d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 4400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-3d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 2900,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-4d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 13000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-4d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 11800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-4d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 10400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-4d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 9100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-4d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 7600,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-4d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 5800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-4d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 3600,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-5d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 16100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-5d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 14700,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-5d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 12800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-5d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 11200,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-5d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 9300,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-5d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 7100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-5d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 4300,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-6d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 19100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-6d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 17400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-6d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 15200,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-6d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 13200,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-6d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 11000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-6d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 8300,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-6d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 5000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-7d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 21800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-7d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 19800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-7d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 17400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-7d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 15000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-7d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 12600,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-7d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 9400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-7d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 5700,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-8d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 23900,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-8d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 21700,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-8d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 19100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-8d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 16400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-8d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 13800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-8d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 10300,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-8d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 6200,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-9d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 26000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-9d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 23600,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-9d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 20700,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-9d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 17900,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-9d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 15000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-9d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 11200,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-9d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 6800,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-unlimited-lte-10d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 28100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-5gb-lte-10d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 25600,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-4gb-lte-10d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 22400,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-3gb-lte-10d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 19300,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-2gb-lte-10d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 16100,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-1gb-lte-10d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 12000,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'usimsa-JP-500mb-lte-10d-esim',
    partnerName: '유심사',
    partnerUrl: 'https://www.usimsa.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 7200,
    description: 'Google maps 데이터 무료, Chat GPT 데이터 무료',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-unlimited-lte-1d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 3500,
    description: '데이터 무제한+로깨비톡 무료통화',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-1d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 2700,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-1d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 2500,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-1d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 2100,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-1d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 1800,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-1d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 1200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-1d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-unlimited-lte-2d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 6600,
    description: '데이터 무제한+로깨비톡 무료통화',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-2d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 5600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-2d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 5300,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-2d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 5200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-2d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 3700,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-2d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 2100,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-2d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 1300,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-unlimited-lte-3d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 8600,
    description: '데이터 무제한+로깨비톡 무료통화',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-3d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 6800,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-3d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 6600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-3d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 5900,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-3d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 4600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-3d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 3000,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-3d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 1700,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-unlimited-lte-4d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 11200,
    description: '데이터 무제한+로깨비톡 무료통화',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-4d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 8800,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-4d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 8400,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-4d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 7600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-4d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 6200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-4d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 4100,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-4d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 2500,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-unlimited-lte-5d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 14000,
    description: '데이터 무제한+로깨비톡 무료통화',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-5d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 11800,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-5d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 11200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-5d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 9900,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-5d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 7900,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-5d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 5600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-5d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 3300,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-unlimited-lte-6d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 16500,
    description: '데이터 무제한+로깨비톡 무료통화',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-6d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 14700,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-6d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 14000,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-6d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 12400,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-6d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 9900,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-6d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 6800,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-6d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 4200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-unlimited-lte-7d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 19000,
    description: '데이터 무제한+로깨비톡 무료통화',
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-7d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 17500,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-7d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 17200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-7d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 15900,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-7d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 13400,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-7d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 8600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-7d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 5100,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-5gb-lte-10d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 24200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-4gb-lte-10d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '4gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 23800,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-3gb-lte-10d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 22500,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-2gb-lte-10d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 17200,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-1gb-lte-10d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 11600,
    name: '',
    region: '',
  },
  {
    id: 'dokkebi-JP-500mb-lte-10d-esim',
    partnerName: '로밍도깨비',
    partnerUrl: 'https://www.rokebi.com/',
    countryCode: 'JP',
    dataPlan: '500mb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 6500,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-1d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 2900,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-1d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 2300,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-1d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 1800,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-1d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 1200,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-2d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 5300,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-2d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 4300,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-2d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 3000,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-2d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 1900,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-3d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 10900,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-3d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 7700,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-3d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 5900,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-3d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 4300,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-3d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 2600,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-4d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 12700,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-4d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 9900,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-4d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 7700,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-4d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 5500,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-4d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 3200,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-5d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 15800,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-5d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 12400,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-5d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 9800,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-5d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 6600,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-5d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 4000,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-6d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 18000,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-6d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 15700,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-6d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 11500,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-6d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 4600,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-7d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 20300,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-7d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 17200,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-7d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 13200,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-7d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 9200,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-7d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 5200,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-8d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 22300,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-8d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 19400,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-8d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 15000,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-8d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 10300,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-8d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 5800,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-9d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 24600,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-9d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 21800,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-9d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 16900,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-9d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 11500,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-9d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 6600,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-unlimited-lte-10d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 26800,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-5gb-lte-10d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '5gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 24500,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-3gb-lte-10d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '3gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 18600,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-2gb-lte-10d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 12600,
    name: '',
    region: '',
  },
  {
    id: 'dosirak-JP-1gb-lte-10d-esim',
    partnerName: '도시락이심',
    partnerUrl: 'https://pkgtour.naver.com/products/wifidosirak/eSIM-JAPAN-20260619',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 7500,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-1d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 1,
    type: 'esim',
    price: 1200,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-2d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 2,
    type: 'esim',
    price: 1900,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-unlimited-lte-3d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 10000,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-3d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 3,
    type: 'esim',
    price: 2600,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-unlimited-lte-4d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 13200,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-4d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 4,
    type: 'esim',
    price: 3200,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-unlimited-lte-5d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 16000,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-5d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 5,
    type: 'esim',
    price: 4000,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-6d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 6,
    type: 'esim',
    price: 4600,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-unlimited-lte-7d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 22000,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-7d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 5200,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-8d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 8,
    type: 'esim',
    price: 5700,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-9d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 9,
    type: 'esim',
    price: 6600,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-unlimited-lte-10d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 30900,
    name: '',
    region: '',
  },
  {
    id: 'maaltalk-JP-1gb-lte-10d-esim',
    partnerName: '말톡',
    partnerUrl: 'https://store.maaltalk.com/goods/goods_view.php?goodsNo=1000000265',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 10,
    type: 'esim',
    price: 7400,
    name: '',
    region: '',
  }
];

export const ESIM_PARTNER_OFFERS: EsimProduct[] = enrichEsimOffers(RAW);
