/** AUTO-GENERATED — npm run sync:esim (data/esim-offers.csv) */
import type { EsimProduct } from '../types';
import { enrichEsimOffers } from './esimOfferEnrich';

const RAW: EsimProduct[] = [
  {
    id: 'partner-a-jp-1gb-lte-7d-esim',
    partnerName: '제휴사 A',
    partnerUrl: '',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 6900,
    description: 'QR 즉시 발송',
    name: '',
    region: '',
  },
  {
    id: 'partner-b-jp-1gb-lte-7d-esim',
    partnerName: '제휴사 B',
    partnerUrl: '',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 7200,
    description: 'SoftBank·Docomo',
    name: '',
    region: '',
  },
  {
    id: 'partner-c-jp-1gb-lte-7d-esim',
    partnerName: '제휴사 C',
    partnerUrl: '',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 7500,
    name: '',
    region: '',
  },
  {
    id: 'partner-a-jp-1gb-5g-7d-esim',
    partnerName: '제휴사 A',
    partnerUrl: '',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: '5g',
    days: 7,
    type: 'esim',
    price: 8900,
    description: '5G 지역 한정',
    name: '',
    region: '',
  },
  {
    id: 'partner-a-jp-2gb-lte-7d-esim',
    partnerName: '제휴사 A',
    partnerUrl: '',
    countryCode: 'JP',
    dataPlan: '2gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 9900,
    name: '',
    region: '',
  },
  {
    id: 'partner-a-jp-unlimited-lte-7d-esim',
    partnerName: '제휴사 A',
    partnerUrl: '',
    countryCode: 'JP',
    dataPlan: 'unlimited',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 14900,
    description: 'FUP 3Mbps',
    name: '',
    region: '',
  },
  {
    id: 'partner-c-jp-1gb-lte-7d-usim',
    partnerName: '제휴사 C',
    partnerUrl: '',
    countryCode: 'JP',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'usim',
    price: 7900,
    description: '인천공항 T1·T2 수령',
    name: '',
    region: '',
  },
  {
    id: 'partner-a-th-1gb-lte-7d-esim',
    partnerName: '제휴사 A',
    partnerUrl: '',
    countryCode: 'TH',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 5900,
    name: '',
    region: '',
  },
  {
    id: 'partner-b-th-1gb-lte-7d-esim',
    partnerName: '제휴사 B',
    partnerUrl: '',
    countryCode: 'TH',
    dataPlan: '1gb',
    speed: 'lte',
    days: 7,
    type: 'esim',
    price: 6200,
    name: '',
    region: '',
  },
  {
    id: 'partner-a-us-1gb-lte-15d-esim',
    partnerName: '제휴사 A',
    partnerUrl: '',
    countryCode: 'US',
    dataPlan: '1gb',
    speed: 'lte',
    days: 15,
    type: 'esim',
    price: 12900,
    description: 'AT&T·T-Mobile',
    name: '',
    region: '',
  }
];

export const ESIM_PARTNER_OFFERS: EsimProduct[] = enrichEsimOffers(RAW);
