import type { Company } from '../types';

const PLACEHOLDER_IMAGE =
  'https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80';

function externalCompany(
  partial: Pick<Company, 'id' | 'name' | 'externalBookingUrl'> & Partial<Company>
): Company {
  return {
    isAirpickPartner: false,
    is_indoor: true,
    supports_indoor: true,
    supports_outdoor: true,
    base_price: 0,
    base_days: 1,
    extra_day_price: 0,
    rating: 0,
    reviews_count: 0,
    features: [],
    image_url: PLACEHOLDER_IMAGE,
    terminals: ['T1', 'T2'],
    isOpen: true,
    ...partial,
  };
}

/** 에어픽 미입점 주차대행 업체 (실제 요금표 기준) */
export const externalParkingCompanies: Company[] = [
  externalCompany({
    id: 'airport-valet',
    name: '에어포트 주차대행 (실내)',
    externalBookingUrl: 'http://www.air-port.co.kr/',
    pricingProfile: 'airport-pricing',
    supports_indoor: true,
    supports_outdoor: false,
    is_indoor: true,
  }),
  externalCompany({
    id: 'gate-valet',
    name: '게이트 주차대행',
    externalBookingUrl: 'https://xn--o79ak6j18s2nb9zg78lk2e.com/',
    indoorPricingProfile: 'gate-indoor-pricing',
    outdoorPricingProfile: 'gate-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'mampyeonhan-valet',
    name: '맘편한 주차대행',
    externalBookingUrl: 'https://www.xn--vk1bu3ki7n26csym9ncdj.com/',
    pricingProfile: 'mampyeonhan-pricing',
    supports_indoor: false,
    supports_outdoor: true,
    is_indoor: false,
  }),
  externalCompany({
    id: 'plain-valet',
    name: '플레인 주차대행',
    externalBookingUrl: 'https://www.xn--vk1bk9g0xpmob95gcwqfza.com/',
    pricingProfile: 'plain-pricing',
    supports_indoor: false,
    supports_outdoor: true,
    is_indoor: false,
  }),
  externalCompany({
    id: 'danyeowa-valet',
    name: '다녀와 주차대행',
    externalBookingUrl: 'https://www.xn--260b34apc815g99ch3fiyt.com/',
    pricingProfile: 'danyeowa-pricing',
    supports_indoor: false,
    supports_outdoor: true,
    is_indoor: false,
  }),
  externalCompany({
    id: 'atelier-valet',
    name: '아뜰리엔 주차대행',
    externalBookingUrl: 'http://www.xn--oy2b15snmay04b.com/',
    pricingProfile: 'atelier-outdoor-pricing',
    supports_indoor: false,
    supports_outdoor: true,
    is_indoor: false,
  }),
  externalCompany({
    id: 'basecamp-valet',
    name: '베이스캠프 주차대행',
    externalBookingUrl: 'https://basecamp.io.kr/',
    indoorPricingProfile: 'basecamp-indoor-pricing',
    outdoorPricingProfile: 'basecamp-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'honest-valet',
    name: '정직한 주차대행',
    externalBookingUrl: 'https://honestvalet.co.kr/',
    indoorPricingProfile: 'honest-indoor-pricing',
    outdoorPricingProfile: 'honest-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'onair-valet',
    name: '온에어 파킹',
    externalBookingUrl: 'http://www.xn--oh5b1b3n868a8yc.com/',
    pricingProfile: 'onair-indoor-pricing',
    supports_indoor: true,
    supports_outdoor: false,
    is_indoor: true,
  }),
  externalCompany({
    id: 'parkingone-valet',
    name: '파킹원 주차대행',
    externalBookingUrl: 'https://www.parkingone.co.kr/',
    pricingProfile: 'parkingone-indoor-pricing',
    supports_indoor: true,
    supports_outdoor: false,
    is_indoor: true,
  }),
  externalCompany({
    id: 'seven-valet',
    name: '세븐주차대행',
    externalBookingUrl: 'https://www.7park.co.kr/',
    pricingProfile: 'seven-indoor-pricing',
    supports_indoor: true,
    supports_outdoor: false,
    is_indoor: true,
  }),
  externalCompany({
    id: 'cou-valet',
    name: '쿠파킹',
    externalBookingUrl: 'https://www.xn--2l7bopy9c.com/',
    pricingProfile: 'cou-indoor-pricing',
    supports_indoor: true,
    supports_outdoor: false,
    is_indoor: true,
  }),
  externalCompany({
    id: 'fly-valet',
    name: '플라이 파킹',
    externalBookingUrl: 'https://www.flyparking.co.kr/',
    pricingProfile: 'fly-outdoor-pricing',
    supports_indoor: false,
    supports_outdoor: true,
    is_indoor: false,
  }),
  externalCompany({
    id: 'numberone-valet',
    name: '넘버원 주차대행',
    externalBookingUrl: 'https://xn--x50b59a12pjvkpvchzgiyt.com/',
    indoorPricingProfile: 'numberone-indoor-pricing',
    outdoorPricingProfile: 'numberone-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'hyundai-valet',
    name: '현대주차대행',
    externalBookingUrl: 'http://현대주차.com',
    indoorPricingProfile: 'hyundai-indoor-pricing',
    outdoorPricingProfile: 'hyundai-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'myeongpum-valet',
    name: '명품 주차대행',
    externalBookingUrl: 'https://www.xn--vk1bp6lo3m26ci7nfpb.com/',
    indoorPricingProfile: 'myeongpum-indoor-pricing',
    outdoorPricingProfile: 'myeongpum-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'air25-valet',
    name: '에어25시 주차대행',
    externalBookingUrl: 'https://www.xn--25-435j07g8d.com/',
    indoorPricingProfile: 'air25-indoor-pricing',
    outdoorPricingProfile: 'air25-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'chungho-valet',
    name: '청호 주차대행',
    externalBookingUrl: 'https://www.chunghoparking.com/',
    indoorPricingProfile: 'chungho-indoor-pricing',
    outdoorPricingProfile: 'chungho-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'royal-valet',
    name: '로얄파킹',
    externalBookingUrl: 'http://www.royalparking.kr/',
    indoorPricingProfile: 'royal-indoor-pricing',
    outdoorPricingProfile: 'royal-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'onmaeum-valet',
    name: '온마음 주차대행',
    externalBookingUrl: 'https://xn--vk1bp2ksslo7azzdhuhiyt.com/',
    pricingProfile: 'onmaeum-outdoor-pricing',
    supports_indoor: false,
    supports_outdoor: true,
    is_indoor: false,
  }),
  externalCompany({
    id: 'cube-valet',
    name: '큐브 주차대행',
    externalBookingUrl: 'https://www.cubevalet.com/',
    pricingProfile: 'cube-valet-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'blue-valet',
    name: '블루 파킹',
    externalBookingUrl: 'https://www.blueparking.co.kr/',
    pricingProfile: 'blue-indoor-pricing',
    supports_indoor: true,
    supports_outdoor: false,
    is_indoor: true,
  }),
  externalCompany({
    id: 'mirae-valet',
    name: '미래주차',
    externalBookingUrl: 'http://www.xn--hj2bz6fwto26c.com/',
    pricingProfile: 'mirae-indoor-pricing',
    supports_indoor: true,
    supports_outdoor: false,
    is_indoor: true,
  }),
  externalCompany({
    id: 'plus-valet',
    name: '플러스 주차대행',
    externalBookingUrl: 'http://xn--vk1b96gh9kvrg98dcwqfza.com/',
    indoorPricingProfile: 'plus-indoor-pricing',
    outdoorPricingProfile: 'plus-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
  externalCompany({
    id: 'chacha-valet',
    name: '차차 주차대행',
    externalBookingUrl: 'http://www.차차주차대행.com',
    indoorPricingProfile: 'chacha-indoor-pricing',
    outdoorPricingProfile: 'chacha-outdoor-pricing',
    supports_indoor: true,
    supports_outdoor: true,
  }),
];

/** @deprecated externalParkingCompanies 사용 */
export const EXTERNAL_PARKING_COMPANIES = externalParkingCompanies;
