/**
 * data/sitemap/urls.json → public/sitemap.xml
 *
 * 사용:
 *   npm run sitemap
 * build / deploy 시 자동 실행됨.
 *
 * 새 랜딩을 올리면 urls.json 의 urls[] 에 path 추가 후 npm run sitemap.
 * planned[] 는 문서용(사이트맵에 넣지 않음).
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const configPath = path.join(root, 'data/sitemap/urls.json');
const partnersPath = path.join(root, 'data/partners/pages.json');
const outPath = path.join(root, 'public/sitemap.xml');

const EXCLUDE_PREFIXES = ['/my', '/r/', '/admin', '/api/'];

function todayYmd() {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Seoul',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(new Date());
}

function normalizePath(p) {
  const raw = String(p ?? '').trim();
  if (!raw || raw === '/') return '/';
  return raw.startsWith('/') ? raw : `/${raw}`;
}

function isExcluded(pathname) {
  if (pathname === '/my') return true;
  return EXCLUDE_PREFIXES.some((prefix) => pathname === prefix || pathname.startsWith(prefix));
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatPriority(value) {
  const n = Number(value);
  if (!Number.isFinite(n)) return '0.5';
  return Math.min(1, Math.max(0, n)).toFixed(1);
}

async function main() {
  const raw = await readFile(configPath, 'utf8');
  const config = JSON.parse(raw);
  const base = String(config.baseUrl || '').replace(/\/+$/, '');
  if (!base) {
    throw new Error('data/sitemap/urls.json: baseUrl 이 필요합니다.');
  }

  const lastmodDefault = todayYmd();
  const entries = [];
  const seen = new Set();

  for (const item of config.urls ?? []) {
    const pathname = normalizePath(item.path);
    if (isExcluded(pathname)) {
      console.warn(`[sitemap] skip excluded: ${pathname}`);
      continue;
    }
    if (seen.has(pathname)) {
      console.warn(`[sitemap] skip duplicate: ${pathname}`);
      continue;
    }
    seen.add(pathname);

    const loc = pathname === '/' ? `${base}/` : `${base}${pathname}`;
    entries.push({
      loc,
      lastmod: item.lastmod || lastmodDefault,
      changefreq: item.changefreq || 'weekly',
      priority: formatPriority(item.priority ?? 0.5),
    });
  }

  // 입점 공개 URL — pages.json 과 자동 병합 (허브 + 각 id)
  try {
    const partnersRaw = await readFile(partnersPath, 'utf8');
    const { partners } = JSON.parse(partnersRaw);
    const partnerPaths = ['/partners/'];
    if (Array.isArray(partners)) {
      for (const p of partners) {
        const id = String(p?.id || '').trim();
        if (id) partnerPaths.push(`/partners/${id}/`);
      }
    }
    for (const pathname of partnerPaths) {
      if (seen.has(pathname)) continue;
      seen.add(pathname);
      entries.push({
        loc: `${base}${pathname}`,
        lastmod: lastmodDefault,
        changefreq: 'weekly',
        priority: pathname === '/partners/' ? '0.8' : '0.7',
      });
    }
  } catch (err) {
    console.warn(`[sitemap] partners merge skipped: ${err.message}`);
  }

  if (entries.length === 0) {
    throw new Error('sitemap에 넣을 URL이 없습니다. data/sitemap/urls.json 을 확인하세요.');
  }

  const body = entries
    .map(
      (e) => `  <url>
    <loc>${escapeXml(e.loc)}</loc>
    <lastmod>${escapeXml(e.lastmod)}</lastmod>
    <changefreq>${escapeXml(e.changefreq)}</changefreq>
    <priority>${escapeXml(e.priority)}</priority>
  </url>`
    )
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by npm run sitemap — edit data/sitemap/urls.json -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

  await writeFile(outPath, xml, 'utf8');

  const planned = (config.planned ?? []).length;
  console.log(`[sitemap] wrote ${entries.length} urls → public/sitemap.xml`);
  if (planned > 0) {
    console.log(`[sitemap] ${planned} planned paths (not included until moved to urls[])`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
